### PR TITLE
Application Files Re-Organization

### PR DESCRIPTION
**Pull request by jbarzilai**
I'm starting the process of re-organizing the application.  I'm following [John Papa's Angular style guide](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md) as the template for what I'm doing.

This first bit of work is the moving of all the files into the general right structure.

    /
      /app - All application code
      /content - Sass, stylesheets, images, static files, etc
      /scripts
        /data - Data files (for now)
      /thirdparty - Third party scripts/sass

### CODE REVIEW

**Comment by jbarzilai** [comment]
The more I think about it, the more I'm thinking that the data files should all move to the app folder as well.    That way all of our code is in the app folder, bar none, and all of the third party scripts/sass is in the third-party folder.
@Asmor I think that is likely something that you can do in your fork/branch for the IDs modification if you agree, that way we avoid the conflicts.  Thoughts?

**Comment by Asmor** [comment]
I'd like to have the SCSS files for specific modules/components kept with their associated script and HTML files. This is in line with the guidelines you're using

> Note: Do not structure your app using folders-by-type. This requires moving to multiple folders when working on a feature and gets unwieldy quickly as the app grows to 5, 10 or 25+ views and controllers (and other features), which makes it more difficult than folder-by-feature to locate files.

So e.g. battle-tracker.js, battle-tracker.html, and battle-tracker.scss should always be together.

**Comment by jbarzilai** [comment]
That makes sense.  I was matching the pattern I used at work, but I believe that was done for other reasons.
Thus, I have moved the sass files back into the app folder.  However, I haven't moved them back into the partials folders as those are going away in the future.

**Comment by jbarzilai** [comment]
FYI, the more I look at this the more I'm not sure what I like.  Let's talk about it when you've got time next week.  Maybe I'll have an idea then.

**Comment by jbarzilai** [comment]
Per our email discussions we aren't going to go forward with this pull request, we are going to wait for further work in #29.
I don't see a way to delete this pull request.  Should we just close it?

**Pull request closed without merging**
