### PR TITLE
Volo's Guide to Monsters: Complete

### PR DESCRIPTION
**Pull request by chisaipete**
I've finished adding ALL the monsters, plus their environments.  I think it's all correct and good to go.

### CODE REVIEW

**Comment by Asmor** [comment]
This mostly looks good. But why is the Illithilich commented out?

**Comment by chisaipete** [comment]
It was a variant sidebar monster, I wasn't sure if others had been added
from other sources.  There are a few more, such as other types of cows that
I didn't add, but I could.

**Comment by Asmor** [comment]
Yes, please do. See the Mind Flayer Arcanist for an example of a monster that comes from a sidebar.

**Comment by chisaipete** [comment]
Okay, I'll review it later today and update the pull request. ☺

**Comment by jbarzilai** [comment]
@Asmor One other thing you might want to think about doing is update the source categories.  Depending on where you think Volo's might go, it probably counts for "All Books" and "Core".

This code is in modules/encounter-builder/encounter-builder.js around line 124 in case @chisaipete wants to update it.

**Comment by chisaipete** [comment]
Good point, I wasn't sure which source we wanted to put this in. I guess it
counts as Monster Manual number 2, not really a campaign sourcebook. I'll
make the update.

**Comment by Asmor** [comment]
I'm inclined to not consider Volo's guide to be core, although I can see arguments either way. What do you guys think?

**Comment by jbarzilai** [comment]
Like Connor said, it feels like a Monster Manual 2.0.  But I guess it
depends on what you consider "core".  I'm not entirely sure what that term
should represent.

We could consider core to be what most people are going to want as their
default.  In which case, since Volo's seems really popular, I don't think
including it would be that bad.  Or it will drive more sales of it, either
way I'm cool with that. :-)

That said, I can see it the other way and don't have too strong of an
opinion.

Joe

On Sun, Nov 20, 2016 at 12:40 PM Ian Toltz notifications@github.com wrote:

I'm inclined to not consider Volo's guide to be core, although I can see
arguments either way. What do you guys think?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
https://github.com/Asmor/5e-monsters/pull/23#issuecomment-261796112, or mute
the thread

**Comment by Asmor** [comment]
Ok, let's go ahead and make it core.

Regarding the conflicts, I had to make some changes to files to add cache busting, and that involved altering the indentation on this file. The contents of the file didn't change in any appreciable way, so it should be simple enough to port your changes over. Sorry for the conflict.

**Comment by chisaipete** [comment]
That's fine, I'm resolving the conflict and adding a few variant creatures
now.

**Comment by chisaipete** [comment]
I pulled from the head of the repo, I thought that would resolve the conflict?  I guess I'm just not seeing it?

**Comment by Asmor** [comment]
I'm not all that great with Git or GitHub myself. I just did some investigation and it looks like everything is fine; the conflicted file has my changes, and it has Volo's guide in it as well. So let me know when you're all done with your stuff and I'll figure out whatever needs to be done to get it merged.

**Comment by chisaipete** [comment]
I'm all done! I was just hoping GitHub would say it merged cleanly.

**Comment by Asmor** [comment]
Ok, it's merged in! Thanks again for your hard work!

**Comment by Asmor** [comment]
And it's live now

**Pull request merged**
