### PR TITLE
Random encounter table

### LINKED ISSUE #91: Random Encounter Table
Would it be possible to go through and add monsters to a pool then generate the encounters from that pool so you could basically create a Random Encounter Table with your campaign in mind?

Thanks for all your work by the way. Love the program.

### PR DESCRIPTION
**Pull request by elsoybean**
fix #91

### CODE REVIEW

**Comment by Asmor** [comment]
This is very nice. There's one problem, though. The width of the dropdown for selecting a table is unbounded, so if you have a very long name (which, if you've selected a number of creatures, is the default), the dropdown becomes arbitrarily large. Please add a max-length to it (and make sure to check the smallest breakpoint, where form elements change and realign).

Also, you left a console.log in the `library.service.js` file.

Please take care of those issues and this can be merged.

Thanks!

**Comment by elsoybean** [comment]
Will do! I also knew there'd be conflicts if you merged the filter warning, so I have a little cleaning up to do anyway. Coming right up... thanks!

**Comment by Asmor** [comment]
The conflicts are pretty simple, it's just stuff that's been added in the same locations. If that and the console.log had been the only issues I would have taken care of it myself, but the width thing was just beyond the level of effort I've got the motivation for at the moment.

**Comment by elsoybean** [comment]
I hear that! Should be fixed now. Thanks for all the work you've put in, by the way... awesome tool, and a pleasure to work on.

**Comment by Asmor** [comment]
Changed the max width of the dropdown to 300px. I realize this doesn't quite work on the narrower screens, but 605px just felt too large to me.

Thanks!

**Comment by elsoybean** [comment]
Yeah I thought 300 made more sense too,  I just didn’t want to unilaterally make it smaller than the other controls under 768px.

**Pull request merged**
