### PR TITLE
Redesign Phase 1 - Building the Encounter

### PR DESCRIPTION
**Pull request by jbarzilai**
Hi all,
I've completed the first phase of the redesign I've been working on for Kobold.club.  I use this site a ton and realized it could do with a lot of design love.  So a web site designer at my work and I decided to spend some free time and redesign it.  Hopefully it keeps to the core of what @Asmor was trying to do and he likes what I've done.

There's a lot of code changed so I wanted to try to give a good write-up of everything I did and why.

### Design Goals:
- Keep the core site structure and behavior the same, to avoid alienating core users.
- Update the design to a more modern look and feel
- Focus on information hierarchy to prioritize the more important components of the site
  - Make prime components such as party layout, search, and monster names/quantities bigger
  - Minimized the noise of less important components like some of the filters and the legend of difficulties
- Even out the information density in different parts of the site to make it easier to use and read
  - Redistribute the dead space in the monster table to provide more information in the same space
- Allow basic usage through mobile/tablet or at least make it possible to use the site awkwardly.

### Coding Goals:
- Convert the project to a node module for easier development
  - This made my life easier but could just as easily be ripped out
- Add in Twitter Bootstrap for an easy interface baseline

### My Redesign Phases
Since this is such a large scale redesign, I really wanted to do it in parts.  I'm organizing myself to finish things in phases.
**Phase 1.** Redesign the Encounter Builder page.  This will likely be the biggest part.
**Phase 1.5.** Code refactoring, further design tweaks, any bug fixes.  The main part of this is a LARGE scale refactoring to move the site from using Angular partials to using the more modern patterns of Angular Directives and/or Components.  I don't want to do this without @Asmor giving the go ahead though.
**Phase 2.** Redesign the Manage Encounters page
**Phase 3.** Redesign the Run Encounter workflow and pages.

**One note about the pull**: I don't have pull request #21 included.  And also, we are going to want to update some of the Set Sources choices for Volo's I think.

Ok, now on to the reveal.  I've taken a bunch of screenshots below to hopefully give everyone a good idea of the new design without needing to boot up my fork.  
**I really want to hear everyone's feedback on this, thanks!**

### For a baseline, here is the current site.
base page old

### And here is the redesign.
base page new

### I also annotated the new site to show off the different design goals I was talking about.
base page new annotated

### Here are the old vs new designs when looking at a built encounter.
full encounter old
full encounter new

### This is the new legend.  I've moved it out of the way so that it is only open if someone needs to understand the colors.
legend new

### Customizing the sources you were using was a bit of an awkward process.  I've tried to streamline it.
set sources old
set sources new

### Lastly, here is a comparison of the old vs the new on a mobile device.  I did a bit of work but I would like to do a lot more.
mobile old
mobile new

### CODE REVIEW

**Comment by Asmor** [comment]
This looks phenomenal.

> Phase 1.5. Code refactoring, further design tweaks, any bug fixes. The main part of this is a LARGE scale refactoring to move the site from using Angular partials to using the more modern patterns of Angular Directives and/or Components. I don't want to do this without @Asmor giving the go ahead though.

This was, I think, the second thing I ever did in Angular, and I'm quite embarrassed by that. If you want to put in the work to refactor things out to directives, you're more than welcome. I fully support that, but I didn't know to do it when I first wrote this and I don't really actively work on it much anymore.

Before I merge this pull request, I just wanted to confirm that node isn't necessary for deployment (I think I mentioned this to you in my email, but my web host doesn't allow node, and my "deployment" is basically just "git pull").

**Comment by jbarzilai** [comment]
No need to be ashamed for this code.  You did a ton of work just to put it together and learn Angular enough to get it this far.  I'll start working on the refactor soon.  I'm definitely having a good time working on something that people use.

You make a really good point about node.  My intention was that node would be a dev-only resource for launching an http server and compiling sass.  I went back and double checked and node isn't required.  The only production pieces I added were added via CDN or downloaded manually to the third-party folder and checked it.  So we should be good.

On a side note, I don't do github much.  Once you've merged this pull request, how can I continue development?  Is there a way to rebase or merge your base master branch into my fork again?

**Comment by Asmor** [comment]
I'm not all that familiar with forking myself, but I believe you just continue working in your fork and submit a new pull request whenever you think it's ready. You can also use fetch to make sure your fork is up to date with this version.

http://www.dataschool.io/simple-guide-to-forks-in-github-and-git/
https://git-scm.com/docs/git-fetch

**Comment by Asmor** [comment]
I've merged this in and will be updating the site with it in a bit (it's actually live at http://kobold.club/fight-new right now). Just want to play with it a bit and make sure nothing major was broken.

I do have a couple suggestions for future changes...
1. Make the CR column either center- or left-aligned
2. Make the column widths static (right now they jump around when you page depending on the contents of that particular page).

Just testing some values out real quick, I think these would make good good settings for the columns (although I'm looking at this on desktop, so might not make sense on mobile)

Source: 200px
Alignment: 120px
Type: 120px
Size: 100px
CR: 30px
Name: *
Button: 49px

**Comment by Asmor** [comment]
Oh, the text in the buttons for running an encounter has lost its vertical centering

Current: 
image

Original:
image

**Comment by jbarzilai** [comment]
Yeah, I was noticing the messed up buttons on the other pages.  I spent minimal time on those pages.  I think I'll spend a bit of time this evening changing all those buttons to Bootstrap (giving them the "btn btn-sm" classes) which will fix their styling.  A lot of what I did was to rip out the custom css in favor of Bootstrap's which is a bit more elaborate and exact.

Good idea on the column widths.  I'll try out a few things.  The super long source names usually muck up things so some jumping around may be a good thing, but standardizing the columns with mostly same-sized data should be easy enough.

**Comment by Asmor** [comment]
It's live now at the regular address. Last thing I noticed was that it doesn't highlight when you have filters enabled (i.e. under the old one, if I specified an environment, that filter would get a yellow background to show it was active). This is helpful because otherwise it's easy to forget you have filters active...

For the sources, I'm thinking it might make sense to give every source a short hand (e.g. Monster Manual = MM) and use that, with the full name in a title attribute so you can see it on mouse over. Could also add the full names to the legend.

**Comment by jbarzilai** [comment]
Hmm, seems to be broken for me.

**Comment by Asmor** [comment]
I think there's a caching issue with the CSS or something. I had to clear my cache to get it working.

**Comment by jbarzilai** [comment]
Seems to be some kind of caching issue.  It REALLY wanted to hang onto the other html files it was pulling in.

**Comment by jbarzilai** [comment]
Yep, all working now.

**Comment by Asmor** [comment]
Oh, it was the HTML and not the CSS? That makes sense... The browser's caching of HTML files that it fetches via AJAX ignores reloading the page, even if you do the shift+reload

Still really obnoxious, and probably going to be a problem for visitors... I'll look into adding a cache-busting param to the files

**Comment by jbarzilai** [comment]
Yeah, the CSS is all one big compiled file, so a Shift+F5 fixed that.
However, the other html files didn't want to refresh.

Cache-busting might be a good short term fix.  At my work we use gulp to
compile all the angular files into a single CSS and a single JS/HTML.  It
automatically adds that param.  When I do the refactoring I might use that.

But yeah, for now we're a bit screwed.

**Comment by jbarzilai** [comment]
And in reply to your earlier comment:
I intentionally ditched the highlighting on the filters for now.  If you
feel like you miss it, and its really easy to miss having a filter, I'll
start thinking up another way to highlight them.  Shouldn't be that hard to
do something that brings attention.

Yeah, I deliberated on some kind of way to show what sources were chosen
without having to open the modal.  In the end, I thought this way fine for
now, but annoying, and I'd brainstorm ideas with my designer on Monday.

**Comment by Asmor** [comment]
You're going to want to update your fork before doing any work. Adding cache busting required me to alter the indentations of several files (which had previously just been defining an object, but now need to define a function that returns an object).

I added a new constant for version, and just appended that to all HTML files.

**Comment by Asmor** [comment]
Here are a couple suggestions for highlighting active filters:

image

image

**Comment by jbarzilai** [comment]
Updating my code now.

I like the first suggestion.  I was leaning towards something like that but
maybe trying to make the font bold as well.

**Comment by Asmor** [comment]
FYI, I went ahead and added support for shorter names (the longest one, I think, is HoardSup for the Hoard of the Dragon Queen online supplement. Short names will be used when the screen is narrower than 768px, which is the same break point where the top menu gets folded in.

**Pull request merged**
